openapi: 3.1.0
info:
  title: "Lend a Hand"
  description: ""
  version: 1.0.0
tags:
  - name: emergencies
    description: Requests related to Emergencies
  - name: volunteer
    description: Requests related to Volunteers
  - name: authentication
    description: Requests related to Authentication

paths:
  /emergencies/{emergencyId}:
    get:
      tags:
        - Emergency
      summary: Fetch emergency
      operationId: fetchEmergency
      parameters:
        - in: path
          name: emergencyId
          schema:
            type: UUID
          required: true
          description: Emergency UUID
      responses:
        '200':
          description: Successfully fetched emergency
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FetchEmergencyResponse'
        '404':
          description: Emergency has not been found in the database
        '409':
          description: An unknown error has occurred
    delete:
      tags:
        - Emergency
      summary: Delete emergency
      operationId: deleteEmergency
      parameters:
        - in: path
          name: emergencyId
          schema:
            type: UUID
          required: true
          description: Emergency UUID
      responses:
        '200':
          description: Successfully deleted emergency
        '404':
          description: Emergency has not been found in the database
        '409':
          description: An unknown error has occurred
    put:
      tags:
        - Emergency
      summary: Update emergency
      operationId: updateEmergency
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateEmergencyRequest'
      parameters:
        - in: path
          name: emergencyId
          schema:
            type: UUID
          required: true
          description: Emergency UUID
      responses:
        '200':
          description: Successfully updated emergency
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FetchEmergencyResponse'
        '409':
          description: An unknown error has occurred
  /emergencies:
    get:
      tags:
        - emergencies
      summary: Fetch emergencies
      operationId: fetchEmergencies
      responses:
        '200':
          description: Successfully fetched emergencies
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FetchEmergenciesResponse'
        '409':
          description: An unknown error has occurred
    post:
      tags:
        - emergencies
      summary: Add a new emergency
      operationId: addNewEmergency
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateEmergencyRequest'
      responses:
        '201':
          description: Emergency created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateEmergencyResponse'
        '400':
          description: Bad request
        '409':
          description: An unknown error has occurred

  /emergencies/{emergencyId}/resign:
    delete:
      tags:
        - Volunteer
      summary: Resign from emergency
      operationId: resignFromEmergency
      parameters:
        - in: path
          name: emergencyId
          schema:
            type: UUID
          required: true
          description: Emergency UUID
      responses:
        '200':
          description: Successfully resigned from emergency
        '409':
          description: An unknown error has occurred

  /emergencies/{emergencyId}/singup:
    post:
      tags:
        - Volunteer
      summary: Sign up for emergency
      operationId: signUpForEmergency
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpRequest'
      parameters:
        - in: path
          name: emergencyId
          schema:
            type: UUID
          required: true
          description: Emergency UUID
      responses:
        '200':
          description: Successfully signed up for emergency
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignUpResponse'
        '409':
          description: An unknown error has occurred

  /emergencies/{emergencyId}/status:
    get:
      tags:
        - Volunteer
      summary: get volunteering status
      operationId: volunteerStatus
      parameters:
        - in: path
          name: emergencyId
          schema:
            type: UUID
          required: true
          description: Emergency UUID
      responses:
        '200':
          description: Successfully checked user status
          content:
            application/json:
              schema:
                type: boolean
                example: true
        '409':
          description: An unknown error has occurred

  /registration:
    post:
      tags:
        - authentication
      summary: Register a new user
      operationId: registration
      $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
        '400':
          description: Bad request
        '409':
          description: An error has occurred
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  details:
                    type: string
              examples:
                emailExists:
                  summary: Email already registered
                  value:
                    error: "A user with this email address already exists"
                unknownError:
                  summary: An unknown error has occurred
                  value:
                    error: "An unknown error has occurred"

components:
  schemas:
    EmergencyType:
      type: string
      enum:
        - CLEANUP_ASSISTANCE
        - FOOD_SUPPLY
        - WATER_SUPPLY
        - MEDICINE_SUPPLY
        - HYGIENE_PRODUCTS
        - REPAIR_ASSISTANCE

    FetchEmergencyResponse:
      properties:
        id:
          type: string
          example: "8096c0dd-64f0-49cf-9282-8dfbb788ff0a"
        userId:
          type: string
          example: "5cd65a54-d6d5-4e3b-886c-65e3b59e232e"
        title:
          type: string
          example: "Zbiórka gruzu po powodzi"
        description:
          type: string
          example: "Mój dom został zniszczony przez powódź i potrzebuję pomocy w sprzątaniu oraz zbieraniu gruzu. Każda ręka do pracy się liczy!"
        type:
          $ref: '#/components/schemas/EmergencyType'
          example: "CLEANUP_ASSISTANCE"
        status:
          type: boolean
          example: false
        latitude:
          type: number
          format: float
          example: 21.00
        longitude:
          type: number
          format: float
          example: 52.15
        startDate:
          type: string
          format: date-time
          example: "2024-11-12T14:30:00Z"

    FetchEmergenciesResponse:
      type: object
      properties:
        emergencies:
          type: array
          items:
            $ref: '#/components/schemas/FetchEmergencyResponse'

    SignUpRequest:
      properties:
        id:
          type: string
          example: "8096c0dd-64f0-49cf-9282-8dfbb788ff0a"

    SignUpResponse:
      properties:
        id:
          type: string
          example: "8096c0dd-64f0-49cf-9282-8dfbb788ff0a"
        userId:
          type: string
          example: "b4408dc3-a595-447b-aa18-e5c7a4718917"
        emergencyId:
          type: string
          example: "9be5234f-6f31-49b8-b7bd-200d8a532911"

    CreateEmergencyRequest:
      properties:
        id:
          type: string
          example: "8096c0dd-64f0-49cf-9282-8dfbb788ff0a"
        title:
          type: string
          example: "Zbiórka gruzu po powodzi"
        description:
          type: string
          example: "Mój dom został zniszczony przez powódź i potrzebuję pomocy w sprzątaniu oraz zbieraniu gruzu. Każda ręka do pracy się liczy!"
        type:
          $ref: '#/components/schemas/EmergencyType'
          example: "CLEANUP_ASSISTANCE"
        latitude:
          type: number
          format: float
          example: 21.00
        longitude:
          type: number
          format: float
          example: 52.15
        startDate:
          type: string
          format: date-time
          example: "2024-11-12T14:30:00Z"

    CreateEmergencyResponse:
      properties:
        id:
          type: string
          example: "8096c0dd-64f0-49cf-9282-8dfbb788ff0a"
        userId:
          type: string
          example: "5cd65a54-d6d5-4e3b-886c-65e3b59e232e"
        title:
          type: string
          example: "Zbiórka gruzu po powodzi"
        description:
          type: string
          example: "Mój dom został zniszczony przez powódź i potrzebuję pomocy w sprzątaniu oraz zbieraniu gruzu. Każda ręka do pracy się liczy!"
        type:
          $ref: '#/components/schemas/EmergencyType'
          example: "CLEANUP_ASSISTANCE"
        status:
          type: boolean
          example: false
        latitude:
          type: number
          format: float
          example: 21.00
        longitude:
          type: number
          format: float
          example: 52.15
        startDate:
          type: string
          format: date-time
          example: "2024-11-12T14:30:00Z"

    UpdateEmergencyRequest:
      properties:
        title:
          type: string
          example: "Zbiórka gruzu po powodzi"
        description:
          type: string
          example: "Mój dom został zniszczony przez powódź i potrzebuję pomocy w sprzątaniu oraz zbieraniu gruzu. Każda ręka do pracy się liczy!"
        type:
          $ref: '#/components/schemas/EmergencyType'
          example: "CLEANUP_ASSISTANCE"
        latitude:
          type: number
          format: float
          example: 21.00
        longitude:
          type: number
          format: float
          example: 52.15
        startDate:
          type: string
          format: date-time
          example: "2024-11-12T14:30:00Z"

    RegisterRequest:
      properties:
        id:
          type: string
          example: "8096c0dd-64f0-49cf-9282-8dfbb788ff7a"
        firstName:
          type: string
          example: "Jan"
        lastName:
          type: string
          example: "Nowak"
        password:
          type: string
          example: "12345"
        email:
          type: string
          example: "xyz@example.com"
        phoneNumber:
          type: string
          example: "123456789"

    RegisterResponse:
      properties:
        id:
          type: string
          example: "8096c0dd-64f0-49cf-9282-8dfbb788ff7a"
        firstName:
          type: string
          example: "Jan"
        lastName:
          type: string
          example: "Nowak"
        password:
          type: string
          example: "12345"
        email:
          type: string
          example: "xyz@example.com"
        phoneNumber:
          type: string
          example: "123456789"
        role:
          type: string
          example: "USER"
        createdAt:
          type: string
          format: date-time
          example: "2024-11-14T18:40:30.4512961"